### ISSUE TITLE
Mod suggestion: stances

### ISSUE THREAD

**Issue by TheLGD27** [zediious/tpfz-sprinkles#100]
As said in title the stances mod would be awesome. i love the option for a variety of movesets. I think itd be cool to have the community vote for which animations theyd like. maybe voting would be unnecessary if there are only 4 viable options depending on the weapon set. idk how hard itd be to integrate or how time consuming itd be but i personally think it would fit right in. i alos dont know if its already in the works but i didnt find it when searching for it in the github.

https://www.nexusmods.com/skyrimspecialedition/mods/40484

I closed and reposted to see if I could add a label but idk how.

**Comment by zediious** [comment]
I'll be getting issue templates set up to make it more intuitive to submit bugs here :)

This is definitely something I've had on my mind for some time. The issue I see mostly is that if keeping with a relatively grounded animation style, it would be tough to find quality animations for all of the stances.

The main approach I'm planning to take is applying certain special animations with specific/unique weapons equipped, or when having a specific perk late in a tree.

I will close this one out for now as I'm not planning on implementing stances in that way currently. Thank you tons for the suggestion though!
