### ISSUE TITLE
Morthal Jarl chair bug

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#101]
Sometimes when entering the Morthal hall the jarl is floating and not sat in the chair. Was about to take a picture until she stood up and reset her position 😅

**Comment by zediious** [comment]
Have not been able to re-produce her floating above the seat after quite a few tries. I would chalk this up to random skyrim things. However if you find you can reproduce this, please post some images and try uploading your save as well!

**Comment by zediious** [comment]
I will close this one out as I have yet to see this occur or have another report.
