### ISSUE TITLE
Solitude random attack on guard 

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#105]
a random npc with a mask and black robes attacking a guard out of nowhere. the npc is immortal. kept getting back up again.

**Comment by zediious** [comment]
Hi! Going to make issue templates for this tracker, to make this a bit easier in the future.

The only thing that rings a bell for me is the demented mages that Mihail’s mod’s have roaming the roads sometimes that fit the image, but they can be killed. Have not seen them in a city either.

If this happens again, try to open the console with the ~ key, click the NPC in question, and get the information at the bottom right of the screen in a screenshot. That will help immensely with identifying these types of things.

**Comment by zediious** [comment]
I will close this one out as I have yet to see this occur or have another report. Will definitely keep my eye out for random masked homicidal man.
