### ISSUE TITLE
Suggestion: Chopping wood cycle 

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#106]
There's a mod on nexus that I remember using once where the character is forever chopping wood instead of having to click the chopping block again to repeat the cycle. 

It's a small addition but I feel like it would be a lot less tedious than vanilla chopping

**Comment by zediious** [comment]
This mod has been added in the next version :) Thank you for the suggestion!! Definitely a good idea

https://www.nexusmods.com/skyrimspecialedition/mods/26888
