### ISSUE TITLE
Subtitle stuck 

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#107]
this bandit orc got killed by 3 wolves I was about distant but then when they killed him and went closer to kill wolves and loot him. and his like subtitle thing is still on my screen even he dead.  Also he disappear when he died but after like a min or something his corpse reappeared.

**Comment by zediious** [comment]
This is a known bug with Maximum Carnage unfortunately. It's common for people that were gored while saying something to have the line stuck on the screen until you leave.

I'll close this out as it's been a long-running bug with the mod, and I certainly don't want to remove it :p
