### ISSUE TITLE
Fish out of water 🐟

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#108]
As we can see, we have a fish out of water 😅😂
![1712320758073343148195183472648](https://github.com/zediious/tpfz-sprinkles/assets/130263797/d7c2a310-3d62-496f-96b6-75dca87945eb)

**Comment by zediious** [comment]
They're quite the troopers living it out without water :p

I'll be trying to patch this mod to move the fish into actual water

**Comment by zediious** [comment]
This mod has been removed in the next version. They are placed correctly in the water, but they often clip through the floor in areas like that. I've seen it many times myself.
