### ISSUE TITLE
Bald female 

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#109]
Not sure if she's actually meant to be bald but her name is (Una) saw her walking around in solitude

**Comment by zediious** [comment]
Resolved by applying high poly head facepart to her. Unsure why this wasn’t added by the synthesis patcher, though it’s possible I removed it in error.

![image](https://github.com/zediious/tpfz-sprinkles/assets/12464778/0e76be36-cafd-4d0f-9b13-faac6a724c0a)
