### ISSUE TITLE
Shield bashing enemy triggers backstab animation with instant kill - probable fix included

### ISSUE THREAD

**Issue by tslnox** [zediious/tpfz-sprinkles#110]
**Way to reproduce:** 
have a weapon equipped, attack NPC and press shield bash before the attack animation ends. I'm not exactly sure if it's only shield bash or both shield bash and attack at once.

**Reddit thread about it**
https://www.reddit.com/r/skyrimmods/comments/y5pnph/bashing_in_the_middle_of_an_animation_always/

**Possible fix**
A known bug with Valhalla Combat, there exists a fix https://www.nexusmods.com/skyrimspecialedition/mods/97195

**Comment**
I haven't tested it thoroughly, I just added the fix right after ValhallaCombat.esp and run game, exited inn and killed about 10 guards. Before the fix I killed every guard from almost full health with the backstab anim (and many other, even bandit chief 10 levels higher than me) and it even triggered on Zora Fair-Child (so it doesn't care if target is an enemy, friend or follower)

**Modifications to the list**
[loadorder.txt](https://github.com/zediious/tpfz-sprinkles/files/15241121/loadorder.txt)
[modlist.txt](https://github.com/zediious/tpfz-sprinkles/files/15241122/modlist.txt)

**Comment by zediious** [comment]
Have added this fix in the next version. Thanks a ton for pointing this out!!
