### ISSUE TITLE
CTD after dying when reloading back into game. 

### ISSUE THREAD

**Issue by Kontakt13** [zediious/tpfz-sprinkles#111]
Hi, title says it all. After each death the game crashed while reloading back in. It was pretty frequent since start of play through but now it's every death.

**Comment by zediious** [comment]
Resolvable by adding https://www.nexusmods.com/skyrimspecialedition/mods/44252 to the list, and placing it above "XP32 Maximum Skeleton Special Extended".

XP32 Maximum Skeleton Special Extended already is installed to not include scripts, so there must be another mod in the list still relying on them in some capacity. This seems to have resolved the issue for most users however, and is in the next version.
