### ISSUE TITLE
companions training ground whiterun table bugged in campfire

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#112]
in the companions training ground where everyone sits to eat. the table is bugged in the campfire cooking station thing.

**Comment by zediious** [comment]
I'll be honest, I'm dumbfounded that I had not seen this. Will make a CK patch to resolve this

**Comment by zediious** [comment]
Patch has been made to separate them both, and patch the navmesh on the porch
