### ISSUE TITLE
sometimes npc's dont use their weapons

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#115]
sometimes npc's dont use their weapons. instead use their fists. like bandits.

**Comment by zediious** [comment]
A lot of the Bandits in the list are "Hand-to-Hand" bandits courtesy of an interaction between the "Lawless" and "Hand-to-Hand" mods. 99% of the time if you see a bandit punching, they are meant to be this way and do more damage/have perks.
