### ISSUE TITLE
Can't learn spells for spell books anymore 

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#117]
Reported this to keep record

EDIT FROM ZED:

From discord: "Cant learn new spells. Reading spell books no longer works, just marks the book as read and nothing happens. Cany provide crash log as it isnt causing one."

This is an issue that seems to rarely occur on saves, due to something specific occurring. Save above was a light-mage character, confirmed issue, whereas I have played a pure mage to level 45 and not had the issue. Unsure exactly what causes it to trigger.

Confirmed that stopping/starting and/or resetting the mod's quest does not resolve the issue. Does not seem related to the value of any of the mod's global's either.

**Comment by zediious** [comment]
Can confirm this is resolvable by removing the mod, loading and saving, re-adding and re-loading.

This has been made possible now by moving the spell tome exclusions previously in ZedPatch3 to it's own plugin/mod.

This will be in the next version (which will be save-safe!)

Continuing to look into why the mod does this, though it will be resolvable going forward.

**Comment by zediious** [comment]
Found that re-installing the mod has resolved this issue on a known affected save. The mod was compacted and flagged, and normal function was seen, it seems that this causes a long-term issue.

Next version of the list will have the mod un-compacted and non-ESL flagged, where the issue doesn't seem to occur/is resolved.
