### ISSUE TITLE
Companions npcs struggle with porch pathing

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#122]
Modlist Version: latest
Modlist Profile: refined

**Describe the Bug**
Sometimes the companions just get stuck at the table where the porch and fire spit is. They struggle to get around it usually teleport through it at times because they can't find correct patching around the table or porch

**Comment by zediious** [comment]
Resolved by moving the table closer to the pillar. Was not able to get NPCs comfortably walking on both sides, they have more space and can walk between fire and table now.
