### ISSUE TITLE
Idolaf battle born Weird cape/armour

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#125]
Modlist Version: latest
Modlist Profile: refined

**Describe the Bug**
Idolaf battleborn in whiterun, if you look at his back there's this weird black thing on his cape? or armour? thought it was a shadow but its not. Might need looking at.

**Comment by zediious** [comment]
![image](https://github.com/user-attachments/assets/4b687d7e-b79e-4adf-9d9b-46f5b52e7675)

He seems to be looking alright in a new save in the in-dev version of the list. I do not believe I changed anything with Idolaf in particular. If you see this again, certainly do get a screenshot!
