### ISSUE TITLE
floating bow after dead bandit

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#126]
Modlist Version: latest
Modlist Profile: refined

So this bug happened to me before in a previous version. Killed this bandit after a floating norse bow was just above its corpse. might be the dismemberment mod. causing it, might the bow itself. not to sure but something to look at.

**Comment by zediious** [comment]
Going to close this issue as we already have one open regarding this :) https://github.com/zediious/tpfz-sprinkles/issues/28
