### ISSUE TITLE
Strange and young man appear randomly on fast travel

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#129]
Modlist Version: latest
Modlist Profile: refined

**Describe the Bug**
strange man spawned in Riverwood kept following me. known bug but posted here to keep record

**Comment by zediious** [comment]
Seems like nonsense to me that these dudes keep spawning as I've commented out the line that does so in the script. I need to do some through testing on it, though the alternative is removing Molag Bal's Inferno as I have apprehensions about using it alongside VIGILANT.

@AggravatedSpoon Have you found if this occurs with a brand new save on the latest version of the list?

**Comment by zediious** [comment]
Molag Bal's Inferno has been removed in the next version of the list.
