### ISSUE TITLE
Suggestion: Replace MCO with BFCO

### ISSUE THREAD

**Issue by Aqua-Markwin** [zediious/tpfz-sprinkles#130]
**Describe the Feature**
BFCO is a new framework that is backwards compatible with MCO animations (after converting them via a tool), that allows the use of Jumping and Swim attacks (in third person only as of writing this). Jump attacks are tied to the combo key in BFCO's MCM, and while I'm not sure where it would be best to map that key to in game, I seem to be doing alright just setting it to E and sheathing my weapon to not power attack while interacting with things. I held off suggesting this before now because it didn't support DMCO until a few days before I made this suggestion, but now it gladly does. 

**Link to Mod(s)**
BFCO: https://www.nexusmods.com/skyrimspecialedition/mods/117052
MCO to BFCO Converter: https://www.nexusmods.com/skyrimspecialedition/mods/119926

**Additional Notes**
BFCO's built in power attack key is also a great replacement to having to use One Click Power Attack NG for people who don't want to use For Honor Power Attack, as it's mentioned that OCPA has issues in this list's wiki.

**Comment by zediious** [comment]
I am currently in the process of integrating this over MCO. I've converted all currently used animations, and they're working great. 

Having removed For Honor Power Attack before doing so, main kink I'm trying to iron out is when using right click for power attack as a hotkey, block is sometimes still being registered. Impossible to "unbind" block as it's attached to many other vanilla functions

**Comment by Aqua-Markwin** [comment]
Is there any problem with just continuing to use For Honor Power Attack for Right Click? I've used it with BFCO before the MCM update and it seemed fine. 

Sorry for closing and reopening, that was a misclick.

**Comment by zediious** [comment]
What I have done is re-enabled For Honor Power Attack (realizing now I am still using the MCO version). I made sure that BFCO is overwriting the single record that conflicts with FOPA.

In BFCO MCM, I've used "Automatic" for holding down left click to continuously light attack, and I set the power attack key the a random key (SCRLK in this case, never touch that). For Honor Power Attack still causes power attack on right click.

This *is* doing what I want, I have not been able to produce a blocking state with power attack. There are times where you can basically "re-start" your attack if you press the power attack key too quickly before the attack finishes, but if you allow it to get about 50%~ through it will chain another.

Most of the movesets are not really designed for this, so sometimes there is some noticeable weirdness as the player quickly gets into position to start the new animation.

Overall it's working quite nicely, continuing to playtest. No less jank than MCO can be at times :p

If you're able to try what I did above, let me know how it goes!

**Comment by Aqua-Markwin** [comment]
I can confirm that using the MCO version of FHPA and creating a patch in xEdit to allow GBlocking(something) to overwrite Blocking(something) from FHPA does fix the weird blocking issue on my end. I've personally gotten weirdly used to setting dodge to be part of sprint like Dark Souls, and setting the combo key to space now, but I think moving FOV is probably better for the average player.

**Comment by zediious** [comment]
Overall it seems to be working great!

Confirmed Elden Counter also still works after converting the animations.

This has been completed for all intents and purposes, and improvements can come with new animations from what we were already using. Will have this in the next version, and continue to tinker with it :)
