### ISSUE TITLE
Missing cart in Dawnstar.

### ISSUE THREAD

**Issue by axtray** [zediious/tpfz-sprinkles#20]
There's no cart in Dawnstar with CFTO, the last reference is Zedpath.esp
![image](https://user-images.githubusercontent.com/80078560/230749989-1159ddaf-d3cb-4e99-9ec0-bde2448e7909.png)

**Comment by zediious** [comment]
This will be fixed in the next update.

The entire cart/horse is inside the wall by default before I patched, but I missed the actual large part of the cart in my first round.

**Comment by zediious** [comment]
This has been fully patched for the next version.
