### ISSUE TITLE
Missing legs wearing Archer Cuirass

### ISSUE THREAD

**Issue by axtray** [zediious/tpfz-sprinkles#21]
As the post says.
![image](https://user-images.githubusercontent.com/80078560/230750524-22f840ad-c0d9-4a6c-99ab-6204f69d73bb.png)

**Comment by zediious** [comment]
Can confirm, will be removing this armor from the list in the next version. I can make NPCs only ever spawn with the full set, but it will still do this when the player equips it how they wish.

https://prnt.sc/1WTXXh4UOiQl
https://prnt.sc/iswpxHVezW7S

**Comment by zediious** [comment]
I've created a HIMBO patch for this mod, which also adds the missing legs. Finishing up the boots and gloves, and then I will refit for CBBE as well.

This process will occur for any mods that lack HIMBO/CBBE BodySlide

https://prnt.sc/ZM1XA0_55x5X - feet nord
https://prnt.sc/FVKiu7F9xh_2 - skinny nord
https://prnt.sc/fVqDplL3w-F- - large nord

**Comment by zediious** [comment]
With the edits to the above comment, this is all fixed up for the next release.

**Comment by zediious** [comment]
After toying with this armor for too long, I've decided it's just not high enough quality. The mesh is *absolutely* not great for females, and I think I would rather fill it in with higher quality and newer armors. This armor will be removed in the next version instead of adding the above refit.
