### ISSUE TITLE
Purple Mesh Poison Rag

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#22]
In the Tanner crafting menu the item (poison rag) is a purple texture

**Comment by zediious** [comment]
This Poison Rag is from the Blowgun mod, unsure why exactly the texture is missing, but I have confirmed it. Will investigate if it can be fixed or if the mod should be removed. https://prnt.sc/Gfbi73bPhC80

**Comment by zediious** [comment]
Have fixed this issue, will be uploading it as a new mod and adding it to the next release

![Screenshot_1718](https://user-images.githubusercontent.com/12464778/231018032-db157071-e152-4454-acce-2bb60cf3f3e7.png)
