### ISSUE TITLE
Missing Legs 

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#23]
A bandit has missing legs its not the archer cuirass its the shoes that's causing the problem

**Comment by zediious** [comment]
It seems like the boots don't entirely make the legs disappear when worn without the cuirass, but it does look pretty wonky. 99% will just remove this armor mod from the list in the next version. https://prnt.sc/LA1sEyqF6bcU

**Comment by zediious** [comment]
I'll close this issue to keep everything inside one https://github.com/zediious/tpfz-sprinkles/issues/21, since we're needing to fix all the armor pieces anyways.
