### ISSUE TITLE
Blurry Show race menu when first creating character

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#24]
This is probably noted already but when you create a new game the character show race menu is blurry

**Comment by zediious** [comment]
Indeed this one is known already :) Unsure exactly what is causing it at the moment. It's some type of light blast effect that occasionally happens before the initial racemenu is opened. Sometimes it takes long enough to occur that it does show in the race menu. Tis being looked into I'll close this one to just have one issue on the subject https://github.com/zediious/tpfz-sprinkles/issues/8
