### ISSUE TITLE
Permanent closed eyes after sleeping

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#26]
After waking up the players eyes are always closed until the save is reloaded. I think there might be a patch for this on nexus.

**Comment by zediious** [comment]
I've observed this a few times, but always forget to worry about it, thank you for posting!

I'll do some research and see what I can find, I definitely recall seeing talk about this issue in the past.

**Comment by zediious** [comment]
As you suspected, this has been fixed by adding the Mfg Fix mod https://www.nexusmods.com/skyrimspecialedition/mods/11669
