### ISSUE TITLE
Prevent cloak clipping through character with Show Player in Menus when paused by adding Skyrim Souls

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#27]
When you open the character inventory and you have the character to the right which you can rotate. When wearing a cloak it clips through weirdly in front through the character.

**Comment by zediious** [comment]
This seems to be a problem with any HDT in this menu. I will look at and see if there's a possible solution.

**Comment by zediious** [comment]
Skyrim Souls RE has been added in dev, with the following menus configured to remain paused:

- Console
- Pause/Quest Journal
- Level up/Skill Menu
- Map Menu
- MCM
