### ISSUE TITLE
Add mods to enhance the Survival Mode Creation when it is in use

### ISSUE THREAD

**Issue by zediious** [zediious/tpfz-sprinkles#31]
I've seen a few mods here and there that enhance the Survival Mode experience. It would be nice to provide players who want to use this with a bit more spice.

**Comment by AggravatedSpoon** [comment]
I found a friendly clean mod that includes all the survival stuff you can want. 
https://www.nexusmods.com/skyrimspecialedition/mods/39414

**Comment by zediious** [comment]
It's more likely I'll go for this https://www.nexusmods.com/skyrimspecialedition/mods/78244

Survival gameplay is truly not a focus of this list. I've made many survival-based lists for myself in the past, and I always find myself dreading the gameplay more than anything. I will however keep the Survival Mode CC in and make sure it works at least agreeably for anyone that wants those elements in a lite form. Anything beyond that and Dirt and Blood won't make it's way to this list.

**Comment by zediious** [comment]
Survival Control Panel has been added. This is as much as as I'll do, beyond making any patches necessary for Survival Mode to work that I may have missed.
