### ISSUE TITLE
Night Blade Gauntlets have some missing texture

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#32]
When the player has night blade gauntlets equipped. Just above both wrists of the character it's invisible. Not showing all of the characters skin.

**Comment by AggravatedSpoon** [comment]
Here is a screen shot 
![IMG_20230411_012200](https://user-images.githubusercontent.com/130263797/231023975-16ae6893-bef2-444e-a441-61d6b05954c4.jpg)

**Comment by zediious** [comment]
Thank you! This will be fixed alongside making HIMBO/CBBE refits for the armor set.

**Comment by zediious** [comment]
In the process of creating bodyslide refits for these armors, I'm finding a pile of problems with all of the armors in the pack nearly, that I'm, seem unable to fix myself. D-Armory will be removed from the mod list in the next release. We'll fill it in with higher quality replacements if possible.
