### ISSUE TITLE
Light fire activator not working

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#33]
Im not sure if this is a bug or not is the player able to light the fire? I'm pressing E but the fire doesn't light. 
![IMG_20230411_012951](https://user-images.githubusercontent.com/130263797/231024938-0fab3918-1bc8-4bc2-bd2c-576f66b29c55.jpg)

**Comment by zediious** [comment]
This is more than likely related to this mod, the mesh for forge fires seems to be pretty wonky in these situations. I have not looked at this yet, as I'm quite sure I will remove Rain Extinguishes Fires (which is save unsafe) and want to do so in a future version that will be marked save-unsafe.

![image](https://user-images.githubusercontent.com/132832032/237176883-2b398aed-59bd-4f70-bbe8-ef7171d29092.png)

**Comment by zediious** [comment]
Rain Extinguishes Fire has been removed in the next version.
