### ISSUE TITLE
Windhelm NPC stuck 

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#34]
First time going in windhelm and this npc is just stuck on a rock stepping forward once and backwards repeatedly 
![IMG_20230411_013957](https://user-images.githubusercontent.com/130263797/231025963-96524708-edb7-4b20-8b59-04e2c170cf3b.jpg)

**Comment by AggravatedSpoon** [comment]
Quick update I've actually just interacted with him and he doesn't have a voice.

**Comment by zediious** [comment]
Are you able to click him in the console and get the information from there?

**Comment by AggravatedSpoon** [comment]
Of course here it is 
![IMG_20230411_015315](https://user-images.githubusercontent.com/130263797/231027399-51c92d16-2227-4d9c-a700-87d488ecc1b8.jpg)

**Comment by zediious** [comment]
What plugin is the NPC added by?

**Comment by AggravatedSpoon** [comment]
He's gone now. Just disappeared. It was an imperial guy though. When I interacted with him I can respond with- "what is an imperial doing in windhelm" so I assume it's a plugin of imperial NPC's in stormcloak cities not sure

**Comment by zediious** [comment]
Yeah, that's weird. Some odd pathing issue possibly and the NPC teleported away. I can say I've never seen an NPC on that rock in the picture in either of my playthroughs.

**Comment by zediious** [comment]
I'll go ahead and close this for now, in the event this happens again we can address it further.
