### ISSUE TITLE
Black textures in night gate inn

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#35]
![IMG_20230412_023837](https://user-images.githubusercontent.com/130263797/231325090-0ccb5230-61f6-4037-8bb2-6c4adac1bf03.jpg)

**Comment by zediious** [comment]
I've confirmed this, very oddly it's a lighting plane object that was last modified by relighting skyrim. Very curious, will get it fixed for next update.
![Screenshot_1722](https://user-images.githubusercontent.com/12464778/231333910-3c51e3fb-ba39-4a1d-a22c-e83d70bb169d.png)

**Comment by zediious** [comment]
This has been fixed for the next update.
![Screenshot_1723](https://user-images.githubusercontent.com/12464778/231335951-572c3728-c4b2-4896-9a4f-d062984459ab.png)
