### ISSUE TITLE
Immersive Display Overhaul popup menu randomly

### ISSUE THREAD

**Issue by AggravatedSpoon** [zediious/tpfz-sprinkles#36]
![IMG_20230412_024259](https://user-images.githubusercontent.com/130263797/231325581-54a3547e-ee0e-4e43-9c4f-82a8511278f9.jpg)

**Comment by zediious** [comment]
This message is from the Immersive Display Overhaul mod. The mod makes use of a specific part of the displays in the world to work. When another mod places displays but does not add that specific node, this message will appear. You can safely just ignore the message, but you may have an issue with a rack nearby. I've personally never actually found a non-functional display rack so far.
