### ISSUE TITLE
Mod Requests: QuickLoot EE & Better SkyUI Config

### ISSUE THREAD

**Issue by m-ft** [zediious/tpfz-sprinkles#37]
With the amount of lootable containers, it can become a chore entering looting menus, especially when opening the wrong container. I think [QuickLootEE](https://www.nexusmods.com/skyrimspecialedition/mods/69980) would be great for QoL, unless there's a compatibility issue I'm unaware of.

A small suggestion, [I think Better SkyUI Config](https://www.nexusmods.com/skyrimspecialedition/mods/49095?tab=files) would make navigating menus a bit easier, especially with the vast amount of new items players can come across, having equipped items sorted to the top for convenience, while also being able to see items sorted by icon. I find that sorting by icon makes it less overwhelming and more intuitive vs. sorting by name.

**Comment by zediious** [comment]
Awesome! Better SkyUI Config looks great, I can admit i do spend more time than I ought to sorting inventories to find whatI want. It also presents everything much nicer by default.

I had initially passed on QuickLootEE due to incompatibility with Better Third Person Selection, but it seems like they are not compatible!

Thank you for the suggestions, they will all more than likely make their way in :)

**Comment by m-ft** [comment]
After a few hours of testing, QuickLootEE doesn't cause any drastic conflicts. Container anims will only play upon manually opening the container, but container anims themselves will still play. There is a conflict with NPC Name Distributor, where the name will overlap the UI, but is a verh easy fix. I just changed the setting from Title to Hyphenated (I'm sure any of the options work, it's up to personal preference; It just looks wonky w/ the Title option)

**Comment by zediious** [comment]
Testing in game, both mods work great! They will be in the next version :)

I must admit I am confused about the incompatibility with NPC Names Distributor. I understand what you're saying and I see how it could happen, but how are you able to have the QuickLoot menu open while also targeting an NPC to see their Title? I tried looking around at all sorts of angles with a generic Helgen guard and a barrel, I could not get both UI elements to show at the same time. I suppose this is an issue when one of those NPCs is just speaking randomly while the QuickLoot UI is open?
![Untitled](https://user-images.githubusercontent.com/12464778/231877315-8ddb1c50-8db7-4f3e-b7ce-ff9b7f59ee74.png)


I'm likely being dense and missing something, do let me know about that :)

**Comment by m-ft** [comment]
Sorry for the confusion! I meant that the way the name is formatted would conflict when looting said NPC (i.e. killing a bandit w/ Title *next line* Bandit, the Bandit part of the name would be on top of the Quick Loot UI).  Here's an image of the small conflict! 
![489830_20230412054500_1](https://user-images.githubusercontent.com/130550195/232182317-11c2cbfa-2f23-49a8-8e24-016857906612.png)

**Comment by zediious** [comment]
> Sorry for the confusion! I meant that the way the name is formatted would conflict when looting said NPC (i.e. killing a bandit w/ Title _next line_ Bandit, the Bandit part of the name would be on top of the Quick Loot UI). Here's an image of the small conflict! ![489830_20230412054500_1](https://user-images.githubusercontent.com/130550195/232182317-11c2cbfa-2f23-49a8-8e24-016857906612.png)

Ahhh I see! I don't know why it did not cross my mind to try looting an enemy with the mod -_- The next version will have the NPC Names Distributor setting changes by default.
