### ISSUE TITLE
Cyrodiilic Master Thief Armor missing female version

### ISSUE THREAD

**Issue by m-ft** [zediious/tpfz-sprinkles#39]
![489830_20230414204819_1](https://user-images.githubusercontent.com/130550195/232181478-e6a83f79-10a7-4447-a076-036a37af84f7.png)
![489830_20230414204825_1](https://user-images.githubusercontent.com/130550195/232181480-2ef89be8-905c-4e2a-bf4b-52d7d848135a.png)

Cyrodiilic Master Thief Armor appears as Leather Armor on Argonian.  Tested it on Faendal (not depicted) and it appears correctly.

**Comment by zediious** [comment]
It seems like this armor does not have a beast version at all, and upon further inspection it lacks a female version as well. I will be adding a female version from the Nexus and seeing if I can make the armor display on Argonian's anyways. It probably looks incredibly messed up on beast races, thus why it's replaced with leather by default. https://www.nexusmods.com/skyrimspecialedition/mods/41362

I will update with the verdict here :)
