### ISSUE TITLE
iEquip randomly not recognizing equipped bows

### ISSUE THREAD

**Issue by m-ft** [zediious/tpfz-sprinkles#40]
When using the Khajiiti ReCurve Bow, using the Left Hand Slot to cycle ammo does not work.  I'm not sure if iEquip is sensing it properly, but it just says my left hand slot queue is empty, in which it is, but it properly displays ammo.  Although it displays my equipped arrows, the amount will not update, nor will it cycle to show my other ammo.

**Comment by m-ft** [comment]
Disregard - cannot replicate anymore, must've been a one time issue (:

**Comment by zediious** [comment]
iEquip can unfortunately be wonky at the best of times. There are a couple other mods like it, but they seem to come with a mountain of other issues instead :(
