### ISSUE TITLE
First Person BTPS Text Cut Off

### ISSUE THREAD

**Issue by m-ft** [zediious/tpfz-sprinkles#42]
I know the pack is meant to be played in third person, but I figured this would still be something you'd like to know. The level of environmental detail you can experience in first person is amazing, but this minor issue really irked me.
![489830_20230416164349_1](https://user-images.githubusercontent.com/130550195/232350187-be2938e3-d573-4c61-9b41-37026e95966f.png)
I remedied this by going to Better Third Person Selection > Widgets > and enabling 3D Widget Enabled in First Person.
![489830_20230416164404_1](https://user-images.githubusercontent.com/130550195/232350278-6384f763-e449-40a0-ba22-dbf0e070e222.png)

**Comment by zediious** [comment]
Oversight on my part! This is fixed for the next version
