### ISSUE TITLE
Elden Sprint alternative

### ISSUE THREAD

**Issue by RustyReplicant** [zediious/tpfz-sprinkles#44]
https://www.nexusmods.com/skyrimspecialedition/mods/78618  https://www.nexusmods.com/skyrimspecialedition/mods/77026?tab=files

SKSE version of Elden Sprint, and one that you can adjust the drain rate yourself.

**Comment by zediious** [comment]
Adjustable Attribute Consumption SKSE has been added to the next version, with Horse stamina consumption enabled out of combat :) Thank you for the enhanced suggestion!
