### ISSUE TITLE
Weapons & Armor Do Not Have Item Previews on Inventory Screen

### ISSUE THREAD

**Issue by m-ft** [zediious/tpfz-sprinkles#45]
All items except for Weapons & Armor all display their items in the inventory screen.
![489830_20230416200432_1](https://user-images.githubusercontent.com/130550195/232368515-b9ca1e07-ea4f-4149-b27a-9745f883a16d.png)
![489830_20230416200503_1](https://user-images.githubusercontent.com/130550195/232368522-9a6283fe-8f09-458c-aafe-2d123a8abab5.png)

**Comment by zediious** [comment]
This is an intentional setting in the Show Player in Menus MCM. I've done that so you can see the player character when equipping weapons/armors, as it will completely block you usually. You can for sure change that setting :)
