### ISSUE TITLE
Crawling Conflict w/ SmoothCam Presets

### ISSUE THREAD

**Issue by m-ft** [zediious/tpfz-sprinkles#46]
All SmoothCam Presets aside from Souls-like are not configured to handle crawling.
![489830_20230416214250_1](https://user-images.githubusercontent.com/130550195/232380628-6f350715-9a42-4b4f-b3e1-56cf189cdd66.png)
Screenshot is using Zed Preset.

**Comment by m-ft** [comment]
![489830_20230416214706_1](https://user-images.githubusercontent.com/130550195/232380774-b45c1bc7-fc3e-4f4b-bacb-3f05f899de92.png)
This is with Souls-like preset.

**Comment by zediious** [comment]
Good catch!I will see if it's possible for me to modify my preset such that it will work with crawling. If not, I will set the Dark Souls preset as default.

**Comment by zediious** [comment]
Have fixed this issue in the default (ZedPreset) preset by adjusting the sneaking height offset. The issue no longer occurs even against steep cliff faces, just as the Souls-Like preset does.
