### ISSUE TITLE
Attempting to Read a Book/Note can rarely Read the One Underneath it

### ISSUE THREAD

**Issue by m-ft** [zediious/tpfz-sprinkles#48]
![489830_20230417015731_1](https://user-images.githubusercontent.com/130550195/232436315-1287a094-87ff-4d43-9afd-1a74f7cf1b85.png)
^^Attempting to read^^
![489830_20230417015736_1](https://user-images.githubusercontent.com/130550195/232436374-583e4549-6e60-46c9-a85a-a0fda0e5faf4.png)
^^The one below it opens^^

I can only get this to happen with unread items, does not occur when the book/note has been read and then reopened.

**Comment by zediious** [comment]
I have an inkling this has to do with the recently added SkyUI configuration, as I have not seen this one before. Will be looked into.

**Comment by m-ft** [comment]
When I made the initial suggestion for the SkyUI Config, I had already been playtesting it and haven't run into this issue before. I was testing it on 0.9.3

**Comment by m-ft** [comment]
Tried looking into this a little more - When first opening inventory, clicking a book/note will select the one underneath; however, staying in the menu, selecting any book/note will open the intended target. Only time I can see this causing any issues would be with spell books [i.e. reading one on accident, or reading the wrong one].

**Comment by m-ft** [comment]
Found a solution, turns out it is because of the config! Here's the [link](https://www.nexusmods.com/skyrimspecialedition/mods/74589?tab=posts)

**Comment by zediious** [comment]
> Found a solution, turns out it is because of the config! Here's the [link](https://www.nexusmods.com/skyrimspecialedition/mods/74589?tab=posts)

Awesome! I will get the changes implemented by that fix into both light/dark configuration files in next version :)
