### ISSUE TITLE
Add Diverse Dragons Collection

### ISSUE THREAD

**Issue by Implode88** [zediious/tpfz-sprinkles#50]
Diverse Dragons would be amazing in this list

**Comment by zediious** [comment]
We're currently using [Infinite Dragon Variants](https://www.nexusmods.com/skyrimspecialedition/mods/74983) to spruce up the appearance of dragons,but [Diverse Dragons Collection](https://www.nexusmods.com/skyrimspecialedition/mods/695) does seem to go a bit beyond just looks, with new attacks/leveling system for these dragons.

It looks great!I recall using an earlier iteration of that mod at some point. I will test it with the load order and see if it works out well with other mods. If so, it will make its way in :) This issue will be updated with the results.

**Comment by zediious** [comment]
For now at least, I've decided that Dragon War in combination with Infinite Dragon Variants is a very much good amount of Dragon variety in the game. There may come a time when I revisit this, but for now I'll close this.
