### ISSUE TITLE
Bugs in Alt start, Hunting in woods with Dog.

### ISSUE THREAD

**Issue by GalenZ** [zediious/tpfz-sprinkles#51]
New unmodified TPFZS install, alt start, Hunters Cabin in Falkreath, AlternatePerspective-HunterStart.esp, numerous mod conflict issues.

1. Two floating deer skulls, already noted in LRS Hunter Extension for Alternate Perspective https://www.nexusmods.com/skyrimspecialedition/mods/53589, console screen shots with ref ids attached.   Recommend disabling the items, and I will be creating an espfe patch to do so.  
![Screenshot (1)](https://user-images.githubusercontent.com/12233767/234412521-e01d3eb3-4d27-492f-b209-e1c9062790bd.png)
![Screenshot (2)](https://user-images.githubusercontent.com/12233767/234412566-dd070cee-1718-4484-9f40-48f701b0ef13.png)

2.  Whole cabin is floating about a foot off the ground.  See attached image for ref ids.
![Screenshot (3)](https://user-images.githubusercontent.com/12233767/234412579-bfa766dc-cbe9-49d7-824d-d806a821756e.png)

3.  At quest end, when I find dead companions, I encountered 3 wolves.  However, all the wolves I got were stuck, unable to move or attack, animal equivalent of t-pose, though their models rotated.   Suspect a Nemesis animation error, as other non-beast actors I met were fully animated.   I suspect this may be due to nemesis not handling creature animations, will experiment.
4. Exiting cabin after quest completion, I ended up some number of yards ways from the cabin door, on top of the next-door shrine.  The navmesh clearly has a bad exit location, probably due to Pilgrim mod.
5. Given the problems with this mod, its limited usefulness, and the fact it takes up a precious esp slot, I'd suggest just removing it from the load order.  It could be changed into an espfe, though at risk of breaking things if anyone tries to touch the cabin interior, and that will not solve the issue of it being right next door to the shrine of Magnus.

**Comment by zediious** [comment]
Yeap, I already created a (evidently poorly made) CK patch between the two. I don't know how I missed my floating house there. I will likely just remove that start addon for the reasons you've listed.

The issue with the wolves is not just limited to this area, it's been observed in a few other locations. I've yet to narrow down exactly what causes it as of now, but am working on it https://github.com/zediious/tpfz-sprinkles/issues/4
