### ISSUE TITLE
Another BIG suggestions thing(new items only this time)

### ISSUE THREAD

**Issue by TheCakeisAlie0** [zediious/tpfz-sprinkles#58]
# New Items
## Armor
[Winged Hussar Armor & Weapons](https://www.nexusmods.com/skyrimspecialedition/mods/89496)
[Barsaebic Ayleid Armor](https://www.nexusmods.com/skyrimspecialedition/mods/85917)
[Rormasu Armor](https://www.nexusmods.com/skyrimspecialedition/mods/73757)
[Argonia Apparel Integration SPID](https://www.nexusmods.com/skyrimspecialedition/mods/88468) _<sub>This mod distributes both the Barsaebic & Rormasu armor into the world</sub>_
[Nordic Steel Helmet](https://www.nexusmods.com/skyrimspecialedition/mods/88288)

## Weapons
[Valermos](https://www.nexusmods.com/skyrimspecialedition/mods/89361)
[Valermos - Dagger](https://www.nexusmods.com/skyrimspecialedition/mods/89617) _<sub>Require base Valermos mod</sub>_
[Violet Bloody Blades](https://www.nexusmods.com/skyrimspecialedition/mods/88656)
[Blades of Chaos](https://www.nexusmods.com/skyrimspecialedition/mods/89815)
[Zaklinak's Weapon Pack](https://www.nexusmods.com/skyrimspecialedition/mods/89573)
[Phoenix Staff](https://www.nexusmods.com/skyrimspecialedition/mods/89863)

**Comment by zediious** [comment]
I've updated your original suggestion post with everything above, so we can keep it all in one place :)
