### ISSUE TITLE
Some Player Home Suggestions

### ISSUE THREAD

**Issue by Vulgaz** [zediious/tpfz-sprinkles#60]
Love the content you've put in so far, but noticed a distinct lack of player homes. Don't know if thats intentional but here are a couple that id love to see added.

> Dovahkiin's Vault SSE []https://www.nexusmods.com/skyrimspecialedition/mods/42237
>Morskom Estate []https://www.nexusmods.com/skyrimspecialedition/mods/33408
>Clockwork (SSE) []https://www.nexusmods.com/skyrimspecialedition/mods/4155 (A whole new quest I know, but damn one of my all time favorite houses).
>NIFLHOLM - Hall Under the Mountain []https://www.nexusmods.com/skyrimspecialedition/mods/8681

**Comment by Vulgaz** [comment]
Saw the other suggestions, makes my suggestions a bit redundant

**Comment by zediious** [comment]
> Saw the other suggestions, makes my suggestions a bit redundant

Thank you for checking the others!! I have bookmarked most of the above for future versions :)
