### ISSUE TITLE
ENB and ReShade Manager

### ISSUE THREAD

**Issue by reallyeasypeasy** [zediious/tpfz-sprinkles#62]
It would simplify the ENB management.

https://www.nexusmods.com/skyrimspecialedition/mods/4143

**Comment by zediious** [comment]
We use Rootbuilder in this list, and this allows us to enable/disable ENBs as mods in Mod Organizer. In my mind, this is much more simple than opening a separate program to change ENBs. To add another preset to the list, you just need to add a mod the Mod Organizer with the same file structure as the existing two ENBs in the list. For now, I'll close this as I don't plan to add ENB Manager/ENB Man

**Comment by reallyeasypeasy** [comment]
Ok cool, good to know that one exists!
