### ISSUE TITLE
Few bugs I found :p

### ISSUE THREAD

**Issue by FenguFengu** [zediious/tpfz-sprinkles#65]
* means I added text here - Zediious

1. Forge fire looks weird
![image](https://github.com/zediious/tpfz-sprinkles/assets/132832032/2b398aed-59bd-4f70-bbe8-ef7171d29092)

2. There are 2 different crafting options for lockpick (same recipe, different number of LP gained *(FIXED FOR NEXT VERSION)
![image](https://github.com/zediious/tpfz-sprinkles/assets/132832032/60191dd0-c696-438c-a23a-c9ba410903be)

3. 1st time reading siphon book make it looks small *(CANNOT RE-PRODUCE)
![image](https://github.com/zediious/tpfz-sprinkles/assets/132832032/3d55c5f8-f257-4423-a60d-6ccf30fb91a8)

4. When enemy has low HP, character is doing killcam animation, but do not do any damage and enemy can't be killed (enemies move, attack etc. and player trying kill the ground). *{FIXED FOR NEXT VERSION)

5. You cannot move in TAB menu (chose perks, eq, magic) when looking at an object/dead body. *(KNOWN ISSUE)

**Comment by zediious** [comment]
1) I'll check this out

2) I will remove that extra recipe, thank you for letting me know!

3) I can't say I've seen this, but you also are meant to get a bunch of smaller notes from reading the book. I'll look at this to confirm.

4) I've only ever experienced this when fighting canines from this issue https://github.com/zediious/tpfz-sprinkles/issues/4 however that was fixed. Which enemies were you fighting when this happened? Was there anything else going on that might have been contributing?

5) This is known https://github.com/zediious/tpfz-sprinkles/issues/43 I've contacted both mod authors and am awaiting a response regarding it. You can still use your Arrow keys to move in that Tween menu in this situation, but it is not optimal.

**Comment by FenguFengu** [comment]
4. I was fighting skewers. Don't know if there was anything contributing to that, i has 2 weapon, one normal, one bound sword, try do attack the rat and did FINISH HIM animation all the time, meanwhile it was running around trying to eat me :p

**Comment by zediious** [comment]
> 4. I was fighting skewers. Don't know if there was anything contributing to that, i has 2 weapon, one normal, one bound sword, try do attack the rat and did FINISH HIM animation all the time, meanwhile it was running around trying to eat me :p

To further expand on this, it seems this can occur rarely when fighting any NPCs. Sometimes the "execution" state does not go through correctly due to an incompatiblity with Precision, causing invincibility for a short time. I'll more than likely remove this mod for the next version, and see if I can find an alternative for the backstab behavior https://www.nexusmods.com/skyrimspecialedition/mods/43436?tab=bugs

**Comment by zediious** [comment]
Carried Forge Fire issue over to open issue regarding the mod I believe is causing that https://github.com/zediious/tpfz-sprinkles/issues/33
