### ISSUE TITLE
The default start option seemed to have led to a game breaking bug

### ISSUE THREAD

**Issue by liconver** [zediious/tpfz-sprinkles#66]
I selected default from the little dragon in the room in Helgen.  I went outside and walked around a bit. Then I slept in the room.  When I woke up this seems to have triggered the vanilla execution scene but from the perspective of the people of Helgen.  When the carts came to a stop basically the game bugged out and the scene stopped progressing.  A few of the characters from the scene were there but doing nothing.  Then I walked around Helgen a bit and the rest of the Characters loaded but nothing was happening.  The issue was during this scene speaking with NPC's did not result in dialogue so it seemed like the game was unplayable.

I guess this is all from the mod Alternate perspective which I've never tried before.  It seems pretty cool but I would think could easily lead to bugs judging on how finicky the game can get is crashing the cart in the opening scene.
By the way, next time I tried a new start I choose the vanilla (Dragonborn) start and going to the keep with the dragon attacking the Dragon was just sitting on the ground for a while blocking the path and not attacking.  Eventually he took off though and the scent progressed.

**Comment by zediious** [comment]
Hi!

>  When the carts came to a stop basically the game bugged out and the scene stopped progressing. A few of the characters from the scene were there but doing nothing. Then I walked around Helgen a bit and the rest of the Characters loaded but nothing was happening. The issue was during this scene speaking with NPC's did not result in dialogue so it seemed like the game was unplayable.

In regards to your first issue, I have never experienced this in any of my play throughs, nor did I experience it testing it 3 times just now. Occasionally, Hadvar will get stuck around his horse for a moment, but he will always be in his proper place by the time he's calling Lokir's name. As such, I must ask If you have modified the list in any way? I am going to make some issue templates to make asking this easier.

> By the way, next time I tried a new start I choose the vanilla (Dragonborn) start and going to the keep with the dragon attacking the Dragon was just sitting on the ground for a while blocking the path and not attacking. Eventually he took off though and the scent progressed.

This is something I have experienced before, even without Alternate Perspective. It doesn't happen every time, however. This is something I'm comfortable pinning on script load during this scene, as it's known to be (as you mentioned) the most script-intense part of the game. I've confirmed that there's no incorrect conflict resolution on the quest or packages in this part of the game.

**Comment by zediious** [comment]
If the first issue mentioned in your post happens to anyone else on an unmodified version of the list, we'll revisit this. Otherwise, I was unable to produce that issue.

Other issues mentioned here have been fixed for the next version.
