### ISSUE TITLE
Sunhelm Widget Conflict

### ISSUE THREAD

**Issue by m-ft** [zediious/tpfz-sprinkles#70]
Sunhelm's widgets are covered by moreHUD's info text
![489830_20230530152414_1](https://github.com/zediious/tpfz-sprinkles/assets/130550195/f4fde0eb-f3e5-42d2-948b-f8c84b2ebdb2)

I remedied this by setting Sunhelm's widgets in the MCM to X: 20 and Y: -20
![489830_20230530152813_1](https://github.com/zediious/tpfz-sprinkles/assets/130550195/3b582170-fbf1-4e60-bd7a-76e90729659e)

Just for anyone that plays with Sunhelm activated (:

**Comment by zediious** [comment]
Thank you for reporting! Oversight on my part. Will get that fixed by default for the next version :)

**Comment by zediious** [comment]
This has been fixed in dev through an MCM Recorder step for Sunhelm added by a new "mod" in the `SURVIVAL MODS (OPTIONAL)` category. It will run on new games, and when running the preset again via the MCM menu.
