### ISSUE TITLE
Better SkyUI Config Overwritten with default Paper UI

### ISSUE THREAD

**Issue by m-ft** [zediious/tpfz-sprinkles#71]
Just noticed that the Better SkyUI Config is not being used in game with the default Paper UI [I have not tested/used the Dark UI yet]. I checked the load order and it is being overridden by Dear Diary - Paper SkyUI Menus. I believe the priorities are 123 and 141 respectively. 

![SkyUIconfig](https://github.com/zediious/tpfz-sprinkles/assets/130550195/1af7530b-903d-4454-a5cb-bfba5cd61812)

**Comment by zediious** [comment]
Hey! My intention with this was to modify the SkyUI config in the Paper UI mod to incorporate the changes from Better SkyUI Config. I know I did this with the "Dear Diary - Dark Mode SkyUI Config".

Can you confirm that the sorting changes are not applying with what you have enabled in your picture for the Paper UI? If so, then I definitely messed that up and will have the file contain relevant changes in the next version.

**Comment by m-ft** [comment]
Here you go!

https://github.com/zediious/tpfz-sprinkles/assets/130550195/1db2f9d7-e8a0-4386-b2fd-3ed6b0f48df3
