### ISSUE TITLE
Spouse will stay in Temple of Mara after wedding ceremony if you choose default location

### ISSUE THREAD

**Issue by ReduxF** [zediious/tpfz-sprinkles#72]
Marrying Isobel from "Interesting NPCs" in Riften will result in her never leaving the Temple of Mara. She will acquire the dialogue of the home you sent her to but she will always remain in the Temple.

**Comment by zediious** [comment]
It seems like this issue only occurs if you choose to have your marriage ceremony in the default Riften, instead of the other new locations provided by Destination Weddings. This will be looked into!

**Comment by zediious** [comment]
This behavior appears to have been fixed in the next version of Destination Weddings, included in the next version of the list.
