### ISSUE TITLE
Reloading save causes all gear to be lost & the mods all start initializing again

### ISSUE THREAD

**Issue by PartySnackss** [zediious/tpfz-sprinkles#78]
I honestly do not know how to explain this. So I downloaded the list, made a new character, and didn't even move until the mods finished initializing, then I saved, reloaded and they took away my hair & eyes, and in the top left corner the mods start initializing again, AND I will spawn in The Sleeping Giant, not in the alternate start room (where I saved). I went further and it will also reset every quest I have done every single time a reload a save. I have no idea what I could've done. 

![20230702202216_1](https://github.com/zediious/tpfz-sprinkles/assets/138420454/20386354-fe64-44b5-a607-7c2ab5be4cf1)

**Comment by PartySnackss** [comment]
![20230702202224_1](https://github.com/zediious/tpfz-sprinkles/assets/138420454/534daed8-2ee9-4de1-937e-8541bade17f8)

**Comment by zediious** [comment]
Heya! This is definitely indicative of some type of problem in the installation. I ask that you reinstall the list, and make sure that you follow all instructions on the wiki when doing so.

You can install the list to the same locations/use the same download folder, and make sure to check the Overwrite box when doing do.

If the problem persists, report back :)

**Comment by PartySnackss** [comment]
Okay! I will do that as soon as I get home! I remember the same thing happening when I used Dragon Edition and I eventually gave up. COULD downloading one or two of my own mods have any effect? I downloaded the Serana dialogue overhaul and Kaidan 2 I think. So I'll test out the modlist completely bare this time!

**Comment by zediious** [comment]
> Okay! I will do that as soon as I get home! I remember the same thing happening when I used Dragon Edition and I eventually gave up. COULD downloading one or two of my own mods have any effect? I downloaded the Serana dialogue overhaul and Kaidan 2 I think. So I'll test out the modlist completely bare this time!

Adding any mods or changing anything at all will absolutely mess up the list if you do not know what you are doing. Make sure to read all of the mandatory sections of the wiki [https://github.com/zediious/tpfz-sprinkles/wiki#warningsdisclaimers](https://github.com/zediious/tpfz-sprinkles/wiki#warningsdisclaimers)

I will mark this as not a bug for now, do update here when you have re-installed the list and re-checked, without changing anything.
