### ISSUE TITLE
suggestion: add info to the Important Hotkeys page about how to configure the hotkeys

### ISSUE THREAD

**Issue by CrazieIvan** [zediious/tpfz-sprinkles#80]
The default hotkeys can't satisfy everyone's play style.  For example, I can never get used to Left Alt to jump and Space to dodge because I've never played any game with this configuration, so I want to swap them.  But I have no idea how to change dodge key to Left Alt.  

The [Important Hotkeys](https://github.com/zediious/tpfz-sprinkles/wiki/Important-Hotkeysl) page already has a nice list of all the modded hotkeys, so it would be great to add instructions next to each one saying which mod handles the hotkey and where to change it.  (MCM, ini file, etc.)

Thanks!  

p.s. And if you could tell me how to change the dodge key, I would appreciate it very much!

**Comment by zediious** [comment]
Heya! This is a good suggestion, and something I should have done previously. I have not modified the current wiki, but have implemented this for the wiki that will be switched to with the next version. You can view there here https://zediious.github.io/tpfzs-docs/docs/mandatory-reading/gameplay-guide/importanthotkeys/
