### ISSUE TITLE
Mod suggestions!

### ISSUE THREAD

**Issue by memjee** [zediious/tpfz-sprinkles#81]
https://www.nexusmods.com/skyrimspecialedition/mods/42068
Rdo! I always thought it was too difficult to put it but I saw other modlist like JaySeerpa's GTS has RDO Lite!

Interesting (Useless) relationships and quests
https://www.nexusmods.com/skyrimspecialedition/mods/94082

**Comment by zediious** [comment]
Thanks for the shout of RDO Lite! I had dismissed the mod some time ago, I absolutely loved its features.

Second suggestion is also fantastic!

Both of these are included in the next version :)
