### ISSUE TITLE
More mod suggestions!

### ISSUE THREAD

**Issue by memjee** [zediious/tpfz-sprinkles#82]
Quests
Great new quest!
[SIRENROOT - Deluge of Deceit at Skyrim Special Edition Nexus - Mods and Community (nexusmods.com)](https://www.nexusmods.com/skyrimspecialedition/mods/70917)
Also cool new quest
[There is No Umbra - Chapter III at Skyrim Special Edition Nexus - Mods and Community (nexusmods.com)](https://www.nexusmods.com/skyrimspecialedition/mods/89089)
Classic one I heard of which might fit your modlist theme (which I haven't tried haha)
[Clockwork (SSE) at Skyrim Special Edition Nexus - Mods and Community (nexusmods.com)](https://www.nexusmods.com/skyrimspecialedition/mods/4155)
Could also fit your modlist theme, I’m tracking this quest, but implementation is probably hard, and a big update is coming eventually.
[Death Consumes All - DLC-Long Quest Mod at Skyrim Special Edition Nexus - Mods and Community (nexusmods.com)](https://www.nexusmods.com/skyrimspecialedition/mods/41910?tab=description)

Location Overhauls
He makes the coolest Orc strongholds, great to check out!
https://www.nexusmods.com/skyrimspecialedition/users/125077838

**Comment by zediious** [comment]
Thank you for your suggestions!

1) Sirenroot is already included in the next version
2) This looks really cool, but it seems to have a few issues in terms of compatibility with with different animations. These are great quest mods, but I feel they belong in a more consolidated list.
3) I've played Clockwork and thought it was great! I have that mod included among my future "Player Home" mods to add. These will come at a later date, when I'll be adding a large amount of player homes. Despite Clockwork having a great quest with it, I've roped it in with the rest of the house mods.
4) As you mentioned, this follows the same vein of There is No Umbra. It's a great concept, but not something I want to have in this list.
5) All four of his Stronghold overhauls are already included in the next version.

Again, thank you tons for you suggestions! I'm always happy to see others want to make the list better.
