### ISSUE TITLE
Armors of the Velothi pt. 2, Bonesaint helmet missing texture patch.

### ISSUE THREAD

**Issue by daffodilian** [zediious/tpfz-sprinkles#85]
The Bonesaint helmet from Armors of the Velothi pt. 2 does not use the texture for the helmets plume. This mod fixes that!

[https://www.nexusmods.com/skyrimspecialedition/mods/83851]([https://www.nexusmods.com/skyrimspecialedition/mods/83851)

**Comment by zediious** [comment]
Thank you for the report! I'll be sure to include this fix in the next version :)
