### ISSUE TITLE
Forgotten Medieval Plate missing arms with other body pieces

### ISSUE THREAD

**Issue by Sw33tsp0t777** [zediious/tpfz-sprinkles#86]
![20231220_010825](https://github.com/zediious/tpfz-sprinkles/assets/154378906/094d068e-c6e3-427e-a9f0-a56f32c0f06f)

**Comment by zediious** [comment]
![Screenshot_1815](https://github.com/zediious/tpfz-sprinkles/assets/12464778/6442e3ba-0316-41f5-8cb5-3ea7b82b8581)

**Comment by zediious** [comment]
Was going in to refit this and realized I don’t really like the look of the armor, it’s just very “clean”. I have removed it in the next version
