### ISSUE TITLE
Consistant Crash in Whiterun Hold

### ISSUE THREAD

**Issue by OGCMayne** [zediious/tpfz-sprinkles#88]
Sorry to bother, but I keep having a consistent issue with crashing right as I cross the bridge in whiterun going towards the big burnt out inn building across from the western watchtower. The crash is never in the same spot, but it's always on or near that specific bridge, I haven't seen anyone else bring it up so I'm not sure if it's specifically a me issue. I also would like to note I have travelled to this specific area on multiple characters for testing purposes and it still happens. These crashes have thus far happened nowhere else in the game.

**Comment by zediious** [comment]
I've spent a lot of time on a companions character, with much time spent in Whiterun and have not been able to reproduce this at all on the latest version. I will close this, definitely re-open if you continue to experience this on an un-modified install of the list.
