### ISSUE TITLE
Suggestion: Add Paulicus Poison Block

### ISSUE THREAD

**Issue by Aqua-Markwin** [zediious/tpfz-sprinkles#93]
Paulicus Poison Block allows the player to block poison with shields and wards, which makes intuitive sense, because you should not be able to get poisoned by something that didn't hit you.

Link to the Mod's Nexus page:
https://www.nexusmods.com/skyrimspecialedition/mods/51046?tab=description

**Comment by zediious** [comment]
This has been added in the next version :) thank you for the suggestion!
