### ISSUE TITLE
Suggestion: Immersive Icons or “B.O.O.B.I.E.S”

### ISSUE THREAD

**Issue by DarkElfMagic** [zediious/tpfz-sprinkles#94]
https://www.nexusmods.com/skyrimspecialedition/mods/89241

I hate what the mod author named it lol but, it has nice icons and adds some, including ones for modded weapons, like the scythes and such.

**Comment by zediious** [comment]
Thank you for the suggestion!!

This mod along with [Kome's Inventory Tweaks](https://www.nexusmods.com/skyrimspecialedition/mods/116713) has been added in the next version.
